services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
